update ci
Updated DagsHub credentials and improved Docker image build process.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,11 +4,12 @@ name: CI Pipeline & Docker Build
 on: [push]
 
 env:
-  # Variable global untuk DagsHub
+  # Kredensial DagsHub (Global)
   DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
   DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
   MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
   MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
+  MLFLOW_TRACKING_URI: "https://dagshub.com/Tikleboy/Eksperimen_SML_StanlyLopez.mlflow"
 
 jobs:
   build-and-deploy:
@@ -23,13 +24,14 @@ jobs:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
-        python-version: '3.9' 
+        python-version: '3.9'
+
     # 3. Install Library
     - name: Install Dependencies
       run: |
         pip install mlflow dagshub pandas scikit-learn seaborn matplotlib mlserver mlserver-mlflow
 
-    # 4. Login ke Docker Hub (Agar bisa upload)
+    # 4. Login ke Docker Hub
     - name: Login to Docker Hub
       uses: docker/login-action@v2
       with:
@@ -40,30 +42,27 @@ jobs:
     - name: Run MLProject (Training)
       working-directory: ./MLProject
       run: |
-        # Jalankan training. Script python akan otomatis membuat file run_id.txt
+        # Gunakan --env-manager=local agar lebih cepat
         mlflow run . --env-manager=local
 
-    # 6. Build Docker Image & Push (BAGIAN ADVANCE)
+    # 6. Build Docker Image & Push
     - name: Build and Push Docker Image
       working-directory: ./MLProject
       run: |
-        # Baca Run ID dari file txt yang dibuat oleh modelling.py tadi
-        if [ -f run_id.txt ]; then
-            RUN_ID=$(cat run_id.txt)
-            echo "Detected Run ID: $RUN_ID"
-        else
-            echo " Error: run_id.txt not found!"
-            exit 1
+        
+        echo " Mencari Run ID terbaru dari DagsHub..."
+        RUN_ID=$(python -c "import mlflow; mlflow.set_tracking_uri('${{ env.MLFLOW_TRACKING_URI }}'); runs = mlflow.search_runs(experiment_names=['CI_Pipeline_Experiment'], order_by=['start_time DESC'], max_results=1); print(runs.iloc[0].run_id)")
+        
+        if [ -z "$RUN_ID" ]; then
+          echo " Error: Tidak ditemukan Run ID!"
+          exit 1
         fi
         
-        # Tentukan Nama Image: username/nama-image:tag
+        echo " Detected Run ID: $RUN_ID"
         IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/sml:latest"
         
-        # Perintah MLflow untuk bungkus model jadi Docker
         echo "Building Docker Image..."
-        # Mengambil model bernama 'model_final' sesuai script python
         mlflow models build-docker -m "runs:/$RUN_ID/model_final" -n "$IMAGE_NAME" --enable-mlserver
         
-        # Upload ke Docker Hub
         echo "Pushing to Docker Hub..."
         docker push "$IMAGE_NAME"
